project_id = "cup-local"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://localhost:5173/app/"
additional_redirect_urls = ["http://localhost:5173/app/**", "http://127.0.0.1:5173/app/**"]
jwt_expiry = 300
signing_keys_path = "./signing_keys.json"
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:55321/auth/v1/callback"
skip_nonce_check = false

[storage]
enabled = false

[analytics]
enabled = false
