/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AudiobooksConversionIdRouteImport } from './routes/audiobooks.$conversionId'
import { Route as ConversionsConversionIdRouteImport } from './routes/conversions.$conversionId'
import { Route as TrialsGrantIdRouteImport } from './routes/trials.$grantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiobooksConversionIdRoute = AudiobooksConversionIdRouteImport.update({
  id: '/audiobooks/$conversionId',
  path: '/audiobooks/$conversionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionsConversionIdRoute = ConversionsConversionIdRouteImport.update({
  id: '/conversions/$conversionId',
  path: '/conversions/$conversionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialsGrantIdRoute = TrialsGrantIdRouteImport.update({
  id: '/trials/$grantId',
  path: '/trials/$grantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/audiobooks/$conversionId': typeof AudiobooksConversionIdRoute
  '/conversions/$conversionId': typeof ConversionsConversionIdRoute
  '/trials/$grantId': typeof TrialsGrantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/audiobooks/$conversionId': typeof AudiobooksConversionIdRoute
  '/conversions/$conversionId': typeof ConversionsConversionIdRoute
  '/trials/$grantId': typeof TrialsGrantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/audiobooks/$conversionId': typeof AudiobooksConversionIdRoute
  '/conversions/$conversionId': typeof ConversionsConversionIdRoute
  '/trials/$grantId': typeof TrialsGrantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/history'
    | '/audiobooks/$conversionId'
    | '/conversions/$conversionId'
    | '/trials/$grantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/history'
    | '/audiobooks/$conversionId'
    | '/conversions/$conversionId'
    | '/trials/$grantId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/history'
    | '/audiobooks/$conversionId'
    | '/conversions/$conversionId'
    | '/trials/$grantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HistoryRoute: typeof HistoryRoute
  AudiobooksConversionIdRoute: typeof AudiobooksConversionIdRoute
  ConversionsConversionIdRoute: typeof ConversionsConversionIdRoute
  TrialsGrantIdRoute: typeof TrialsGrantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobooks/$conversionId': {
      id: '/audiobooks/$conversionId'
      path: '/audiobooks/$conversionId'
      fullPath: '/audiobooks/$conversionId'
      preLoaderRoute: typeof AudiobooksConversionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversions/$conversionId': {
      id: '/conversions/$conversionId'
      path: '/conversions/$conversionId'
      fullPath: '/conversions/$conversionId'
      preLoaderRoute: typeof ConversionsConversionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trials/$grantId': {
      id: '/trials/$grantId'
      path: '/trials/$grantId'
      fullPath: '/trials/$grantId'
      preLoaderRoute: typeof TrialsGrantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HistoryRoute: HistoryRoute,
  AudiobooksConversionIdRoute: AudiobooksConversionIdRoute,
  ConversionsConversionIdRoute: ConversionsConversionIdRoute,
  TrialsGrantIdRoute: TrialsGrantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
